name: Render README and Docs

on:
  workflow_call:
    secrets:
      BOT_APP_ID:
        description: The App ID of the GitHub App
        required: true
      BOT_APP_PRIVATE_KEY:
        description: The private key of the GitHub App
        required: true
  workflow_dispatch:

jobs:
  render-readme:
    name: Render README and Docs
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Generate README and Docs
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          python3 .github/workflows/generate_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "bot-ross"
          git config --global user.email "98030736+bot-ross[bot]@users.noreply.github.com"
          git add README.md docs/
          git commit -m "chore: render README.md and docs" || echo "No changes to commit"
          git push origin main
